name: workflow1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        os: [ubuntu-20.04]
        pkg: [acl,archiver,aria2,axel,base64,bash,bat,bcrypt,bc,bear,bind,blake3,cairo,ccache,cdrtools,cgit,check,cjson,cpio,cppcheck,cpu_features,crosstool-ng,ctop,dash,deno,diffutils,dmalloc,e2fsprogs,elfutils,esbuild,eudev,expect,faac,faad2,fdk-aac,ffmpeg,findutils,fish,folly,gawk,gcc,gdbm,gh,gmake,gnu-binutils,gnu-coreutils,gnupg,gnutls,gnu-which,gobject-introspection]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: ls
        - run: bin/ppkg env

        - run: bin/ppkg setup

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - run: bin/ppkg install ${{ matrix.pkg }}
