name: workflow2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        os: [ubuntu-20.04]
        pkg: [gogs,gomobile,google-benchmark,graphite2,grep,gsed,gtar,gzip,htop,hugo,hwloc,id3lib,ideviceinstaller,jemalloc,jfrog-cli,jq,json-glib,krb5,less,libao,libarchive,libass,libatomic_ops,libb2,libbcrypt,libcaca,libcap-ng,libcddb,libcdio,libcroco,libexif,libgit2,libglob,libical,libimagequant,libirecovery,libisoburn,libmetalink,libnl,libnsl,libphonenumber,libpipeline,libpsl,libressl,libsamplerate,libseccomp,libsigsegv,libsmi,libsodium,libtorrent-rasterbar]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: ls
        - run: bin/ppkg env

        - run: bin/ppkg setup

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - run: bin/ppkg install ${{ matrix.pkg }}
