name: workflow3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        os: [ubuntu-20.04]
        pkg: [libunwind,libwordexp,libxslt,libyuv,links,lmdb,lodepng,lsof,lynx,lzip,mbedtls,mediainfo,mesalink,mosh,mpg123,mpir,musl,neofetch,nginx,ngtcp2,ninja,nodejs,nss3,nss,ntbtls,numactl,nushell,openblas,openlibm,openmpi,openssl-fips,p7zip,packcc,pango,patchelf,pkgconf,pngquant,progress,pth,putty,qrencode,quiche,quickjs,redex,redis,rhash,rlwrap,rsync,rtmpdump,rtorrent]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
