name: workflow5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        pkg: [libcaca,libcap-ng,libcddb,libcdio,libcroco,libexif,libgit2,libglob,libical,libimagequant,libirecovery,libisoburn,libmetalink,libnl,libphonenumber,libpipeline,libpsl,libsamplerate,libseccomp,libsigsegv]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install zpkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/zpkg/master/bin/zpkg
        chmod u+x zpkg
        mv zpkg $(brew --prefix)/bin

    - run: zpkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.zpkg/repos.d/offical
    - run: mv *       ~/.zpkg/repos.d/offical

    - run: zpkg install ${{ matrix.pkg }}
