name: workflow8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15]
        pkg: [openblas,wolfssl,xorriso,xvid,yasm,youtubedr,zsh,zola,shell2http,webhook,esbuild,rtmpdump,rlwrap,ttyrec,ttygif,jfrog-cli,gomobile,itstool,libsodium,libphonenumber,libunwind,archiver,cppcheck,ctop,tinyxml2]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install zpkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/zpkg/master/bin/zpkg
        chmod u+x zpkg
        mv zpkg $(brew --prefix)/bin

    - run: zpkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.zpkg/repos.d/offical/formula
    - run: mv *       ~/.zpkg/repos.d/offical/formula

    - run: zpkg install ${{ matrix.pkg }}
